### ISSUE TITLE
Broken when use it with css transforms

### ISSUE THREAD

**Issue by gugadev** [wwayne/react-tooltip#213]
Good day. I notice a problem when using css transforms. I'm making a draggable component that uses css transforms to move around. After drag the component, the tooltip loses it's uniformity, it isn't shown correctly, some parts simply not seen. Look the picture:

![](http://i.imgur.com/ZE2TriI.jpg)

The component is inside a `<div id="albums"></div>` element with body's width. The `data-tip` element is inside the header (the cog button).

``` javascript
<header
  className="head"
>
  <h3>{this.state.title}</h3>
  <button
    className="settings"
    onClick={this.toggleDrag.bind(this)}
    data-tip
    data-for="toggleDrag"
  >
    <img src={moveIcon} />
  </button>
  <Tooltip
    id="toggleDrag"
    place="right"
    type="dark" 
    effect="solid"
    countTransform={false}
  >
    <span>Toggle Drag</span>
  </Tooltip>
</header>
```

The container's css:

``` css
.portrait {
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.22),
     0 14px 56px rgba(0, 0, 0, 0.25);
  display: inline-block;
  overflow: hidden;
  position: relative;
  user-select: none;
  width: 100%;
}
```

And the header's css:

``` css
.head {
    background-color: rgba(0,0,0,.55);
    left: 0;
    padding: .8rem;
    position: absolute;
    text-align: center;
    top: 0;
    width: 100%;
    z-index: 2;

    & h3 {
      color: rgba(255,255,255,.85);
      font-family: 'Marvel', arial;
      font-size: 2rem;
      margin: 0;
      pointer-events: none;
      text-transform: uppercase;
    }

    & .settings {
      background-color: transparent;
      border: none;
      cursor: pointer;
      height: 20px;
      opacity: .5;
      position: absolute;
      right: 5px;
      top: 5px;
      transition: opacity .25s ease;
      width: 30px;

      & img {
        height: 100%;
        width: 100%;
      }
    }
  }
```
