### ISSUE TITLE
Change darkType triangle width

### ISSUE THREAD

**Issue by orineuman** [wwayne/react-tooltip#284]
Hi,
how do we change the width of the little triangle (border) width? I use the darkType + top option.
Thanks :)

**Comment by huumanoid** [comment]
Hi! It's a bit tricky.
```jsx
<ReactTooltip className="my-tooltip" />
```
```css
.my-tooltip.place-top:after {
border-left: 8px solid transparent !important;
border-right: 8px solid transparent !important;
bottom: -6px !important;
margin-left: -8px !important;
border-bottom-width: 6px !important;
}
```
This is the defaults. Please, try to adjust them.
I suppose there is no other way to archieve this.
What do you think?
