### ISSUE TITLE
Visibility on tooltip hover, custom JSX inside tooltip

### ISSUE THREAD

**Issue by artaommahe** [wwayne/react-tooltip#35]
I think it's really useful things
- prevent tooltip hide on tooltip hover(mb option?)
- allow JSX objects for tooltip content

This things at least let you to add links inside tooltip that can be clicked

**Comment by wwayne** [comment]
> allow JSX objects for tooltip content

This feature has been supported 
Example: http://wwayne.github.io/react-tooltip/
HISTORY.MD: https://github.com/wwayne/react-tooltip/blob/master/HISTORY.md

**Comment by artaommahe** [comment]
Thx :)

**Comment by artaommahe** [comment]
What about tooltip visibility on hover for solid state?

**Comment by wwayne** [comment]
@artaommahe 
Sorry I didn't get you, can you explain more details to me?

**Comment by artaommahe** [comment]
Yep. It's very usefull for placing links in tooltip, e.x.
<ReactTooltip>
  <span>Some description ... <a>read more</a></span>
</ReactTooltip>

now i can't do this cause tooltips hides on parent element hover lost, and it's forced me to use another tooltip lib just for this case

**Comment by wwayne** [comment]
@artaommahe 
Done, you can combine using the feature `class` and `delayHide` of react-tooltip to achieve this:
```
<a data-tip="tooltip" data-class="extra" data-delay-hide="500"></a>
<ReactTooltip />

.extra {
 &:hover {
   visibility: visible !important;
   opacity: 1 !important;
 }
}
```

**Comment by artaommahe** [comment]
Thanks, now i can rid of second tooltip lib :)

**Comment by tnrich** [comment]
Hey there @wwayne , I'm having trouble getting this to work, but I'm not quite sure why..It doesn't seem as if the hover state is being activated when I hover over the tooltip element. If I manually activate the hover state in the chrome console, the tooltip *will* remain popped up.

Here's some code snippets of what I'm trying to do:

```css
.extra {
	&:hover {
		visibility: visible !important;
		opacity: 1 !important;
	}
}

.__react_component_tooltip {
	top: 0px !important;
	left: 0px !important;

	
	
	background: none !important;
	color: black !important;
	&:after{
		border-top: none !important;
	}
	span {
		background: white;
	}
}
```

,,,js
<text
        data-tip
        data-class="extra"
        // data-delay-hide="500"
        data-for={'tooltip' + key}
        key={'text' + key}
        className='dragMe clickable'
        x={x3}
        y={y3}
        style={ {textAnchor: x3 > 0 ? "start" : "end", fontSize: '12px'} }>
        {text + (multipleLabels ? '...' : '')}
      </text>
,,,

Thanks for the help!

Thomas
