### ISSUE TITLE
Question: how to overwrite the left / right padding/margins using css

### ISSUE THREAD

**Issue by StefH** [wwayne/react-tooltip#709]
I currently have this react code:
``` ts
<ReactTooltip place='left' type='info' effect='float' multiline className='tooltip-left' />
```

And this css:
``` css
.tooltip-left {
    border-radius: 0px !important;
    background-color: #007bff !important;
    color: white !important;
    font-size: 0.875rem !important;
}

.multi-line {
    text-align: left !important;
}
```

Which renders **(1)**:
![image](https://user-images.githubusercontent.com/249938/124078766-90657200-da48-11eb-9ac0-b1078e71ea7a.png)

But I actually want the padding / margins left and right be equal to that example button **(2)**.
![image](https://user-images.githubusercontent.com/249938/124078803-9d826100-da48-11eb-9aef-c190cfed2f20.png)

How to do this?

**Comment by ardonjr** [comment]
Tried adding a simple 'padding' ?
I added  `padding: 5px; ` with the following result:

![image](https://user-images.githubusercontent.com/3910372/124173942-09e27c00-daac-11eb-8251-43a1501a1cb2.png)

![image](https://user-images.githubusercontent.com/3910372/124173965-1070f380-daac-11eb-9d1d-da5e0579bb29.png)

**Comment by StefH** [comment]
Correct, for some reason I overlooked this simple fix (I was looking at the `place-left` css class to override).

Final solution:
``` css
.tooltip-left {
    background-color: #007bff !important;
    color: white !important;
    padding: 4px 8px !important; // <---
}
```
