### ISSUE TITLE
How to change opacity of the tooltip?

### ISSUE THREAD

**Issue by AshuGuptaGamer** [wwayne/react-tooltip#757]
Hey, everyone :)
How do I change the opacity of the tooltip?
I have tried this.
```css
.more_server_tooltip {
    background-color: $black !important;
    opacity: 1 !important;
    font-family: helvetica;
}
```
The background color and font-family work. Just the opacity is not working at all.
